project:
  type: book
  output-dir: docs

book:
  title: "Microeconometrics Using R"
  author: "Ritsu Kitagawa"
  date: "5/30/2022"
  repo-url: https://github.com/ritsu1997/metrics-using-r
  repo-actions: [source, edit, issue]
  google-analytics: "G-PEEHJ8EEY1"
  chapters:
    - index.qmd
    - preface.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

